/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * User group information about the actor
 */
export class ActorGroup extends SpeakeasyBase {
  /**
   * Name of the user group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The actor's role in the user group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "role" })
  role?: string;

  /**
   * Canonical reference (unique identifier) for the user group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri?: string;
}

export class ActorOrganization extends SpeakeasyBase {
  /**
   * The actors' role in the organization
   */
  @SpeakeasyMetadata()
  @Expose({ name: "role" })
  role?: string;

  /**
   * Canonical reference (unique identifier) for the organization
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri?: string;
}

/**
 * The Calendly actor that took the action creating the activity log entry
 *
 * @remarks
 *
 * Specific actors:
 *
 * <details>
 * <summary>Calendly System</summary>
 *
 * Used when an action is performed by the Calendly system and not triggered directly by a user interaction.
 *
 * Example:
 * ```json
 * {
 *     "display_name": "Calendly System",
 *     "type": "System"
 * }
 * ```
 *
 * </details>
 *
 * <br />
 *
 * <details>
 * <summary>Calendly Support</summary>
 * Used when an action is performed by Calendly support.
 *
 * Example:
 * ```json
 * {
 *   "display_name": "Calendly Support",
 *   "organization": {
 *     "uri": "https://api.calendly.com/organizations/AAAAAAAAAAAAAAAA"
 *   },
 *   "type": "User",
 *   "uri": "https://api.calendly.com/users/AAAAAAAAAAAAAAAA"
 * }
 * ```
 * </details>
 *
 */
export class Actor extends SpeakeasyBase {
  /**
   * Username of the actor
   */
  @SpeakeasyMetadata()
  @Expose({ name: "alternative_identifier" })
  alternativeIdentifier?: string;

  /**
   * The user's name (human-readable format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "display_name" })
  displayName?: string;

  /**
   * User group information about the actor
   */
  @SpeakeasyMetadata()
  @Expose({ name: "group" })
  @Type(() => ActorGroup)
  group?: ActorGroup;

  @SpeakeasyMetadata()
  @Expose({ name: "organization" })
  @Type(() => ActorOrganization)
  organization?: ActorOrganization;

  /**
   * The type of actor
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: string;

  /**
   * Canonical reference (unique identifier) for the user
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri?: string;
}
