/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AvailabilityRule } from "./availabilityrule";
import { Expose, Type } from "class-transformer";

/**
 * The availability schedule set by the user.
 */
export class AvailabilitySchedule extends SpeakeasyBase {
  /**
   * This is the default Availability Schedule in use.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "default" })
  default: boolean;

  /**
   * The name of this Availability Schedule.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The rules of this Availability Schedule.
   */
  @SpeakeasyMetadata({ elemType: AvailabilityRule })
  @Expose({ name: "rules" })
  @Type(() => AvailabilityRule)
  rules: AvailabilityRule[];

  /**
   * The timezone for which this Availability Schedule is originated in.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "timezone" })
  timezone: string;

  /**
   * A URI reference to this Availability Schedule.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri: string;

  /**
   * A URI reference to a User.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "user" })
  user: string;
}
