/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum CancellationCancelerTypeEnum {
  Host = "host",
  Invitee = "invitee",
}

/**
 * Provides data pertaining to the cancellation of the Event
 */
export class Cancellation extends SpeakeasyBase {
  /**
   * Name of the person whom canceled
   */
  @SpeakeasyMetadata()
  @Expose({ name: "canceled_by" })
  canceledBy: string;

  @SpeakeasyMetadata()
  @Expose({ name: "canceler_type" })
  cancelerType: CancellationCancelerTypeEnum;

  /**
   * Reason that the cancellation occurred
   */
  @SpeakeasyMetadata()
  @Expose({ name: "reason" })
  reason: string;
}
