/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Indicates that the event will be an in-person meeting.
 */
export enum InPersonMeetingTypeEnum {
  Physical = "physical",
}

/**
 * Information about the physical (in-person) event location
 */
export class InPersonMeeting extends SpeakeasyBase {
  /**
   * The physical location specified by the event host (publisher)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "location" })
  location: string;

  /**
   * Indicates that the event will be an in-person meeting.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: InPersonMeetingTypeEnum;
}
