/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * Information about an invitees no show.
 */
export class InviteeNoShow extends SpeakeasyBase {
  /**
   * The moment when the no show was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * Canonical reference (unique identifier) for the associated Invitee
   */
  @SpeakeasyMetadata()
  @Expose({ name: "invitee" })
  invitee: string;

  /**
   * Canonical reference (unique identifier) for the no show
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri: string;
}
