/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A response to a question on a booking page form
 */
export class InviteeQuestionAndAnswer extends SpeakeasyBase {
  /**
   * The invitee's answer to the question
   */
  @SpeakeasyMetadata()
  @Expose({ name: "answer" })
  answer: string;

  /**
   * The position of the question in relation to others on the booking form
   */
  @SpeakeasyMetadata()
  @Expose({ name: "position" })
  position: number;

  /**
   * A question on the invitee's booking form
   */
  @SpeakeasyMetadata()
  @Expose({ name: "question" })
  question: string;
}
