/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class MicrosoftTeamsConferenceDataAudioConferencing extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "conferenceId" })
  conferenceId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "dialinUrl" })
  dialinUrl?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "tollNumber" })
  tollNumber?: string;
}

/**
 * The conference metadata supplied by Microsoft Teams
 */
export class MicrosoftTeamsConferenceData extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "audioConferencing" })
  @Type(() => MicrosoftTeamsConferenceDataAudioConferencing)
  audioConferencing?: MicrosoftTeamsConferenceDataAudioConferencing;

  /**
   * The conference ID provided by Microsoft Teams
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;
}

/**
 * Indicates the current status of the Microsoft Teams conference
 */
export enum MicrosoftTeamsConferenceStatusEnum {
  Initiated = "initiated",
  Processing = "processing",
  Pushed = "pushed",
  Failed = "failed",
}

/**
 * The event location is a Zoom conference
 */
export enum MicrosoftTeamsConferenceTypeEnum {
  MicrosoftTeamsConference = "microsoft_teams_conference",
}

/**
 * Meeting will take place in a Microsoft Teams conference
 */
export class MicrosoftTeamsConference extends SpeakeasyBase {
  /**
   * The conference metadata supplied by Microsoft Teams
   */
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  @Type(() => MicrosoftTeamsConferenceData)
  data: MicrosoftTeamsConferenceData;

  /**
   * Microsoft Teams meeting url
   */
  @SpeakeasyMetadata()
  @Expose({ name: "join_url" })
  joinUrl: string;

  /**
   * Indicates the current status of the Microsoft Teams conference
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status: MicrosoftTeamsConferenceStatusEnum;

  /**
   * The event location is a Zoom conference
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: MicrosoftTeamsConferenceTypeEnum;
}
