/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The user's role in the organization
 */
export enum OrganizationMembershipRoleEnum {
  User = "user",
  Admin = "admin",
  Owner = "owner",
}

/**
 * Information about the user.
 */
export class OrganizationMembershipUser extends SpeakeasyBase {
  /**
   * The URL of the user's avatar (image)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "avatar_url" })
  avatarUrl: string;

  /**
   * The moment when the user's record was created (e.g. "2020-01-02T03:04:05.678123Z")
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * The user's email address
   */
  @SpeakeasyMetadata()
  @Expose({ name: "email" })
  email: string;

  /**
   * The user's name (human-readable format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The URL of the user's Calendly landing page (that lists all the user's event types)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "scheduling_url" })
  schedulingUrl: string;

  /**
   * The portion of URL for the user's scheduling page (where invitees book sessions), rendered in a human-readable format
   */
  @SpeakeasyMetadata()
  @Expose({ name: "slug" })
  slug: string;

  /**
   * The time zone to use when presenting time to the user
   */
  @SpeakeasyMetadata()
  @Expose({ name: "timezone" })
  timezone: string;

  /**
   * The moment when the user's record was last updated (e.g. "2020-01-02T03:04:05.678123Z")
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updated_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt: Date;

  /**
   * Canonical reference (unique identifier) for the user
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri: string;
}

export class OrganizationMembership extends SpeakeasyBase {
  /**
   * The moment when the membership record was created (e.g. "2020-01-02T03:04:05.678123Z")
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * A unique reference to the organization
   */
  @SpeakeasyMetadata()
  @Expose({ name: "organization" })
  organization: string;

  /**
   * The user's role in the organization
   */
  @SpeakeasyMetadata()
  @Expose({ name: "role" })
  role: OrganizationMembershipRoleEnum;

  /**
   * The moment when the membership record was last updated (e.g. "2020-01-02T03:04:05.678123Z")
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updated_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt: Date;

  /**
   * Canonical reference (unique identifier) for the membership
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri: string;

  /**
   * Information about the user.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "user" })
  @Type(() => OrganizationMembershipUser)
  user: OrganizationMembershipUser;
}
