/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Indicates that the event host (publisher) will call the invitee
 */
export enum OutboundCallTypeEnum {
  OutboundCall = "outbound_call",
}

/**
 * Meeting publisher will call the Invitee
 */
export class OutboundCall extends SpeakeasyBase {
  /**
   * The phone number the event host (publisher) will use to call the invitee
   */
  @SpeakeasyMetadata()
  @Expose({ name: "location" })
  location: string;

  /**
   * Indicates that the event host (publisher) will call the invitee
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: OutboundCallTypeEnum;
}
