/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Pagination extends SpeakeasyBase {
  /**
   * The number of rows to return
   */
  @SpeakeasyMetadata()
  @Expose({ name: "count" })
  count: number;

  /**
   * URI to return the next page of an ordered list ("null" indicates no additional results are available)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "next_page" })
  nextPage: string;

  /**
   * Token to return the next page of an ordered list ("null" indicates no additional results are available)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "next_page_token" })
  nextPageToken: string;

  /**
   * URI to return the previous page of an ordered list ("null" indicates no additional results are available)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "previous_page" })
  previousPage: string;

  /**
   * Token to return the previous page of an ordered list ("null" indicates no additional results are available)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "previous_page_token" })
  previousPageToken: string;
}
