/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Question type: name, text input, email, phone, textarea input, dropdown list or radio button list.
 */
export enum QuestionTypeEnum {
  Name = "name",
  Text = "text",
  Email = "email",
  Phone = "phone",
  Textarea = "textarea",
  Select = "select",
  Radios = "radios",
}

/**
 * Routing form questions.
 */
export class Question extends SpeakeasyBase {
  /**
   * The respondent’s option(s) for "select" or "radios" types of questions.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "answer_choices" })
  answerChoices: string[];

  /**
   * Question name (in human-readable format).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * true if an answer to the question is required for respondents to submit the routing form; false if not required.
   *
   * @remarks
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "required" })
  required: boolean;

  /**
   * Question type: name, text input, email, phone, textarea input, dropdown list or radio button list.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: QuestionTypeEnum;

  /**
   * Unique identifier for the routing form question.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uuid" })
  uuid: string;
}
