/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SubmissionQuestionAndAnswer } from "./submissionquestionandanswer";
import { SubmissionTracking } from "./submissiontracking";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Type of the respondent resource that submitted the form and scheduled a meeting.
 */
export enum RoutingFormSubmissionSubmitterTypeEnum {
  Invitee = "Invitee",
  Null = "null",
}

/**
 * Information about a Routing Form Submission.
 */
export class RoutingFormSubmission extends SpeakeasyBase {
  /**
   * The moment the routing form was submitted.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * All Routing Form Submission questions with answers.
   */
  @SpeakeasyMetadata({ elemType: SubmissionQuestionAndAnswer })
  @Expose({ name: "questions_and_answers" })
  @Type(() => SubmissionQuestionAndAnswer)
  questionsAndAnswers: SubmissionQuestionAndAnswer[];

  /**
   * The polymorphic base type for a Routing Form Submission result.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "result" })
  result?: any;

  /**
   * The URI of the routing form that's associated with the submission.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "routing_form" })
  routingForm: string;

  /**
   * The reference to the Invitee resource when routing form submission results in a scheduled meeting.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "submitter" })
  submitter: string;

  /**
   * Type of the respondent resource that submitted the form and scheduled a meeting.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "submitter_type" })
  submitterType: RoutingFormSubmissionSubmitterTypeEnum;

  /**
   * The UTM and Salesforce tracking parameters associated with a Routing Form Submission.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "tracking" })
  @Type(() => SubmissionTracking)
  tracking: SubmissionTracking;

  /**
   * The moment when the routing form submission was last updated.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updated_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt: Date;

  /**
   * Canonical reference (unique identifier) for the routing form submission.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri: string;
}
