/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Event } from "./event";
import { Pagination } from "./pagination";
import { Expose, Type } from "class-transformer";

/**
 * Service response
 */
export class ScheduledEventsResponse extends SpeakeasyBase {
  /**
   * The set of scheduled events matching the criteria
   */
  @SpeakeasyMetadata({ elemType: Event })
  @Expose({ name: "collection" })
  @Type(() => Event)
  collection: Event[];

  @SpeakeasyMetadata()
  @Expose({ name: "pagination" })
  @Type(() => Pagination)
  pagination: Pagination;
}
