/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * All Routing Form Submission questions with answers.
 */
export class SubmissionQuestionAndAnswer extends SpeakeasyBase {
  /**
   * Answer provided by the respondent when the form was submitted.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "answer" })
  answer?: string;

  /**
   * Question name (in human-readable format).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "question" })
  question: string;

  /**
   * Unique identifier for the routing form question.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "question_uuid" })
  questionUuid: string;
}
