/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Indicates that the routing form submission resulted in a redirect to an external URL.
 */
export enum SubmissionExternalUrlResultTypeEnum {
  ExternalUrl = "external_url",
}

/**
 * Information about the external URL Routing Form Submission result.
 */
export class SubmissionExternalUrlResult extends SpeakeasyBase {
  /**
   * Indicates that the routing form submission resulted in a redirect to an external URL.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: SubmissionExternalUrlResultTypeEnum;

  /**
   * The external URL the respondent were redirected to.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value: string;
}
