/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Indicates if the routing form submission resulted in a custom "thank you" message.
 */
export enum SubmissionCustomMessageResultTypeEnum {
  CustomMessage = "custom_message",
}

/**
 * Contains an object with custom message headline and body.
 */
export class SubmissionCustomMessageResultValue extends SpeakeasyBase {
  /**
   * Body text displayed when answers don't match any routes.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "body" })
  body: string;

  /**
   * Headline displayed when answers don't match any routes.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "headline" })
  headline: string;
}

/**
 * Information about the custom message Routing Form Submission result.
 */
export class SubmissionCustomMessageResult extends SpeakeasyBase {
  /**
   * Indicates if the routing form submission resulted in a custom "thank you" message.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: SubmissionCustomMessageResultTypeEnum;

  /**
   * Contains an object with custom message headline and body.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  @Type(() => SubmissionCustomMessageResultValue)
  value: SubmissionCustomMessageResultValue;
}
