/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Indicates that the routing form submission resulted in a redirect to an event type booking page.
 */
export enum SubmissionEventTypeResultTypeEnum {
  EventType = "event_type",
}

/**
 * Information about the event type Routing Form Submission result.
 */
export class SubmissionEventTypeResult extends SpeakeasyBase {
  /**
   * Indicates that the routing form submission resulted in a redirect to an event type booking page.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: SubmissionEventTypeResultTypeEnum;

  /**
   * A reference to the event type resource.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value: string;
}
