/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * Information about the user.
 */
export class User extends SpeakeasyBase {
  /**
   * The URL of the user's avatar (image)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "avatar_url" })
  avatarUrl: string;

  /**
   * The moment when the user's record was created (e.g. "2020-01-02T03:04:05.678123Z")
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * A unique reference to the user's current organization
   */
  @SpeakeasyMetadata()
  @Expose({ name: "current_organization" })
  currentOrganization: string;

  /**
   * The user's email address
   */
  @SpeakeasyMetadata()
  @Expose({ name: "email" })
  email: string;

  /**
   * The user's name (human-readable format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The URL of the user's Calendly landing page (that lists all the user's event types)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "scheduling_url" })
  schedulingUrl: string;

  /**
   * The portion of URL for the user's scheduling page (where invitees book sessions), rendered in a human-readable format
   */
  @SpeakeasyMetadata()
  @Expose({ name: "slug" })
  slug: string;

  /**
   * The time zone to use when presenting time to the user
   */
  @SpeakeasyMetadata()
  @Expose({ name: "timezone" })
  timezone: string;

  /**
   * The moment when the user's record was last updated (e.g. "2020-01-02T03:04:05.678123Z")
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updated_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt: Date;

  /**
   * Canonical reference (unique identifier) for the user
   */
  @SpeakeasyMetadata()
  @Expose({ name: "uri" })
  uri: string;
}
