/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class DeleteOrganizationsUuidMembershipsRequest extends SpeakeasyBase {
  /**
   * The organization membership's unique identifier
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=uuid",
  })
  uuid: string;
}

export class DeleteOrganizationsUuidMembershipsErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class DeleteOrganizationsUuidMembershipsErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: DeleteOrganizationsUuidMembershipsErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => DeleteOrganizationsUuidMembershipsErrorResponseDetails)
  details?: DeleteOrganizationsUuidMembershipsErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

export class DeleteOrganizationsUuidMembershipsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: DeleteOrganizationsUuidMembershipsErrorResponse;

  /**
   * Caller not authorized to perform this action
   */
  @SpeakeasyMetadata()
  errorResponse1?: shared.ErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
