/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetEventTypeAvailableTimesRequest extends SpeakeasyBase {
  /**
   * End time of the requested availability range.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=end_time",
  })
  endTime?: string;

  /**
   * The uri associated with the event type
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=event_type",
  })
  eventType?: string;

  /**
   * Start time of the requested availability range.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=start_time",
  })
  startTime?: string;
}

export class GetEventTypeAvailableTimesErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class GetEventTypeAvailableTimesErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: GetEventTypeAvailableTimesErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => GetEventTypeAvailableTimesErrorResponseDetails)
  details?: GetEventTypeAvailableTimesErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

/**
 * Service Response
 */
export class GetEventTypeAvailableTimes200ApplicationJSON extends SpeakeasyBase {
  /**
   * The set of available times for the event type matching the criteria
   */
  @SpeakeasyMetadata({ elemType: shared.EventTypeAvailableTime })
  @Expose({ name: "collection" })
  @Type(() => shared.EventTypeAvailableTime)
  collection: shared.EventTypeAvailableTime[];
}

export class GetEventTypeAvailableTimesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: GetEventTypeAvailableTimesErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * OK
   */
  @SpeakeasyMetadata()
  getEventTypeAvailableTimes200ApplicationJSONObject?: GetEventTypeAvailableTimes200ApplicationJSON;
}
