/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetScheduledEventsEventUuidInviteesInviteeUuidPathParams extends SpeakeasyBase {
  /**
   * The event's unique identifier
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=event_uuid",
  })
  eventUuid: string;

  /**
   * The invitee's unique identifier
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=invitee_uuid",
  })
  inviteeUuid: string;
}

export class GetScheduledEventsEventUuidInviteesInviteeUuidRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  pathParams: GetScheduledEventsEventUuidInviteesInviteeUuidPathParams;
}

export class GetScheduledEventsEventUuidInviteesInviteeUuidErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class GetScheduledEventsEventUuidInviteesInviteeUuidErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType:
      GetScheduledEventsEventUuidInviteesInviteeUuidErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(
    () => GetScheduledEventsEventUuidInviteesInviteeUuidErrorResponseDetails
  )
  details?: GetScheduledEventsEventUuidInviteesInviteeUuidErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

/**
 * OK
 */
export class GetScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSON extends SpeakeasyBase {
  /**
   * An individual who has been invited to meet with a Calendly member
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resource" })
  @Type(() => shared.Invitee)
  resource: shared.Invitee;
}

export class GetScheduledEventsEventUuidInviteesInviteeUuidResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: GetScheduledEventsEventUuidInviteesInviteeUuidErrorResponse;

  /**
   * Caller not authorized to view event
   */
  @SpeakeasyMetadata()
  errorResponse1?: shared.ErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * OK
   */
  @SpeakeasyMetadata()
  getScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSONObject?: GetScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSON;
}
