/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetUserAvailabilitySchedulesRequest extends SpeakeasyBase {
  /**
   * A URI reference to a user
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=user" })
  user?: string;
}

export enum GetUserAvailabilitySchedules403ApplicationJSONMessageEnum {
  ThisUserIsNotInYourOrganization = "This user is not in your organization",
}

export enum GetUserAvailabilitySchedules403ApplicationJSONTitleEnum {
  PermissionDenied = "Permission Denied",
}

/**
 * Permission Denied
 */
export class GetUserAvailabilitySchedules403ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: GetUserAvailabilitySchedules403ApplicationJSONMessageEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title?: GetUserAvailabilitySchedules403ApplicationJSONTitleEnum;
}

export class GetUserAvailabilitySchedulesErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class GetUserAvailabilitySchedulesErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: GetUserAvailabilitySchedulesErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => GetUserAvailabilitySchedulesErrorResponseDetails)
  details?: GetUserAvailabilitySchedulesErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

/**
 * OK
 */
export class GetUserAvailabilitySchedules200ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: shared.AvailabilitySchedule })
  @Expose({ name: "collection" })
  @Type(() => shared.AvailabilitySchedule)
  collection: shared.AvailabilitySchedule[];
}

export class GetUserAvailabilitySchedulesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: GetUserAvailabilitySchedulesErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * OK
   */
  @SpeakeasyMetadata()
  getUserAvailabilitySchedules200ApplicationJSONObject?: GetUserAvailabilitySchedules200ApplicationJSON;

  /**
   * Permission Denied
   */
  @SpeakeasyMetadata()
  getUserAvailabilitySchedules403ApplicationJSONObject?: GetUserAvailabilitySchedules403ApplicationJSON;
}
