/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetUsersUserUuidWebhooksWebhookUuidRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=webhook_uuid",
  })
  webhookUuid: string;
}

export class GetUsersUserUuidWebhooksWebhookUuidErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class GetUsersUserUuidWebhooksWebhookUuidErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: GetUsersUserUuidWebhooksWebhookUuidErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => GetUsersUserUuidWebhooksWebhookUuidErrorResponseDetails)
  details?: GetUsersUserUuidWebhooksWebhookUuidErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

/**
 * OK
 */
export class GetUsersUserUuidWebhooksWebhookUuid200ApplicationJSON extends SpeakeasyBase {
  /**
   * Webhook Subscription Object
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resource" })
  @Type(() => shared.WebhookSubscription)
  resource: shared.WebhookSubscription;
}

export class GetUsersUserUuidWebhooksWebhookUuidResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Cannot authenticate caller
   */
  @SpeakeasyMetadata()
  errorResponse?: GetUsersUserUuidWebhooksWebhookUuidErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * OK
   */
  @SpeakeasyMetadata()
  getUsersUserUuidWebhooksWebhookUuid200ApplicationJSONObject?: GetUsersUserUuidWebhooksWebhookUuid200ApplicationJSON;
}
