/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Optional cancellation reason.
 */
export class PostScheduledEventsUuidCancellationApplicationJSON extends SpeakeasyBase {
  /**
   * Reason for cancellation
   */
  @SpeakeasyMetadata()
  @Expose({ name: "reason" })
  reason?: string;
}

export class PostScheduledEventsUuidCancellationJsonRequest extends SpeakeasyBase {
  /**
   * Optional cancellation reason.
   */
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody?: PostScheduledEventsUuidCancellationApplicationJSON;

  /**
   * The event's unique indentifier
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=uuid",
  })
  uuid: string;
}

export enum PostScheduledEventsUuidCancellationJson403ApplicationJSONMessageEnum {
  YouAreNotAllowedToCancelThisEvent = "You are not allowed to cancel this event",
  EventInThePast = "Event in the past",
  EventIsAlreadyCanceled = "Event is already canceled",
}

export enum PostScheduledEventsUuidCancellationJson403ApplicationJSONTitleEnum {
  PermissionDenied = "Permission Denied",
}

/**
 * Caller not authorized to perform this action
 */
export class PostScheduledEventsUuidCancellationJson403ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: PostScheduledEventsUuidCancellationJson403ApplicationJSONMessageEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title?: PostScheduledEventsUuidCancellationJson403ApplicationJSONTitleEnum;
}

export class PostScheduledEventsUuidCancellationJsonErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class PostScheduledEventsUuidCancellationJsonErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: PostScheduledEventsUuidCancellationJsonErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => PostScheduledEventsUuidCancellationJsonErrorResponseDetails)
  details?: PostScheduledEventsUuidCancellationJsonErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

/**
 * Created
 */
export class PostScheduledEventsUuidCancellationJson201ApplicationJSON extends SpeakeasyBase {
  /**
   * Provides data pertaining to the cancellation of the Event
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resource" })
  @Type(() => shared.Cancellation)
  resource: shared.Cancellation;
}

export class PostScheduledEventsUuidCancellationJsonResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: PostScheduledEventsUuidCancellationJsonErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Created
   */
  @SpeakeasyMetadata()
  postScheduledEventsUuidCancellationJSON201ApplicationJSONObject?: PostScheduledEventsUuidCancellationJson201ApplicationJSON;

  /**
   * Caller not authorized to perform this action
   */
  @SpeakeasyMetadata()
  postScheduledEventsUuidCancellationJSON403ApplicationJSONObject?: PostScheduledEventsUuidCancellationJson403ApplicationJSON;
}
