/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Optional cancellation reason.
 */
export class PostScheduledEventsUuidCancellationApplicationJSON extends SpeakeasyBase {
  /**
   * Reason for cancellation
   */
  @SpeakeasyMetadata()
  @Expose({ name: "reason" })
  reason?: string;
}

export class PostScheduledEventsUuidCancellationRequest extends SpeakeasyBase {
  /**
   * Optional cancellation reason.
   */
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody?: PostScheduledEventsUuidCancellationApplicationJSON;

  /**
   * The event's unique indentifier
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=uuid",
  })
  uuid: string;
}

export enum PostScheduledEventsUuidCancellation403ApplicationJSONMessageEnum {
  YouAreNotAllowedToCancelThisEvent = "You are not allowed to cancel this event",
  EventInThePast = "Event in the past",
  EventIsAlreadyCanceled = "Event is already canceled",
}

export enum PostScheduledEventsUuidCancellation403ApplicationJSONTitleEnum {
  PermissionDenied = "Permission Denied",
}

/**
 * Caller not authorized to perform this action
 */
export class PostScheduledEventsUuidCancellation403ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: PostScheduledEventsUuidCancellation403ApplicationJSONMessageEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title?: PostScheduledEventsUuidCancellation403ApplicationJSONTitleEnum;
}

export class PostScheduledEventsUuidCancellationErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class PostScheduledEventsUuidCancellationErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: PostScheduledEventsUuidCancellationErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => PostScheduledEventsUuidCancellationErrorResponseDetails)
  details?: PostScheduledEventsUuidCancellationErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

/**
 * Created
 */
export class PostScheduledEventsUuidCancellation201ApplicationJSON extends SpeakeasyBase {
  /**
   * Provides data pertaining to the cancellation of the Event
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resource" })
  @Type(() => shared.Cancellation)
  resource: shared.Cancellation;
}

export class PostScheduledEventsUuidCancellationResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: PostScheduledEventsUuidCancellationErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Created
   */
  @SpeakeasyMetadata()
  postScheduledEventsUuidCancellation201ApplicationJSONObject?: PostScheduledEventsUuidCancellation201ApplicationJSON;

  /**
   * Caller not authorized to perform this action
   */
  @SpeakeasyMetadata()
  postScheduledEventsUuidCancellation403ApplicationJSONObject?: PostScheduledEventsUuidCancellation403ApplicationJSON;
}
