/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The start and end times that delineate the time range for scheduled events data deletion.
 */
export class PostDataComplianceDeletionEventsRequestBody extends SpeakeasyBase {
  /**
   * The scheduled events UTC timestamp at which data deletion should end.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "end_time" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  endTime: Date;

  /**
   * The scheduled events UTC timestamp at which data deletion should begin.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "start_time" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  startTime: Date;
}

export class PostDataComplianceDeletionEventsErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class PostDataComplianceDeletionEventsErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: PostDataComplianceDeletionEventsErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => PostDataComplianceDeletionEventsErrorResponseDetails)
  details?: PostDataComplianceDeletionEventsErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

export class PostDataComplianceDeletionEventsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: PostDataComplianceDeletionEventsErrorResponse;

  /**
   * Forbidden
   */
  @SpeakeasyMetadata()
  errorResponse1?: shared.ErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Accepted
   */
  @SpeakeasyMetadata()
  postDataComplianceDeletionEvents202ApplicationJSONObject?: Record<
    string,
    any
  >;
}
