/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class PostScheduledEventsUuidCancellationMultipartRequest extends SpeakeasyBase {
  /**
   * Optional cancellation reason.
   */
  @SpeakeasyMetadata({ data: "request, media_type=multipart/form-data" })
  requestBody?: Record<string, any>;

  /**
   * The event's unique indentifier
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=uuid",
  })
  uuid: string;
}

export enum PostScheduledEventsUuidCancellationMultipart403ApplicationJSONMessageEnum {
  YouAreNotAllowedToCancelThisEvent = "You are not allowed to cancel this event",
  EventInThePast = "Event in the past",
  EventIsAlreadyCanceled = "Event is already canceled",
}

export enum PostScheduledEventsUuidCancellationMultipart403ApplicationJSONTitleEnum {
  PermissionDenied = "Permission Denied",
}

/**
 * Caller not authorized to perform this action
 */
export class PostScheduledEventsUuidCancellationMultipart403ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: PostScheduledEventsUuidCancellationMultipart403ApplicationJSONMessageEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title?: PostScheduledEventsUuidCancellationMultipart403ApplicationJSONTitleEnum;
}

export class PostScheduledEventsUuidCancellationMultipartErrorResponseDetails extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parameter" })
  parameter?: string;
}

/**
 * Error Object
 */
export class PostScheduledEventsUuidCancellationMultipartErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: PostScheduledEventsUuidCancellationMultipartErrorResponseDetails,
  })
  @Expose({ name: "details" })
  @Type(() => PostScheduledEventsUuidCancellationMultipartErrorResponseDetails)
  details?: PostScheduledEventsUuidCancellationMultipartErrorResponseDetails[];

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}

/**
 * Created
 */
export class PostScheduledEventsUuidCancellationMultipart201ApplicationJSON extends SpeakeasyBase {
  /**
   * Provides data pertaining to the cancellation of the Event
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resource" })
  @Type(() => shared.Cancellation)
  resource: shared.Cancellation;
}

export class PostScheduledEventsUuidCancellationMultipartResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Request is not valid
   */
  @SpeakeasyMetadata()
  errorResponse?: PostScheduledEventsUuidCancellationMultipartErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Created
   */
  @SpeakeasyMetadata()
  postScheduledEventsUuidCancellationMultipart201ApplicationJSONObject?: PostScheduledEventsUuidCancellationMultipart201ApplicationJSON;

  /**
   * Caller not authorized to perform this action
   */
  @SpeakeasyMetadata()
  postScheduledEventsUuidCancellationMultipart403ApplicationJSONObject?: PostScheduledEventsUuidCancellationMultipart403ApplicationJSON;
}
